Vagrant.configure("2") do |config|
 config.vm.define "ubuntu_server" do | linux |
  linux.vm.box = "ubuntu/xenial64"
  linux.vm.hostname = "server-ubuntu.com"
  linux.vm.network :private_network, ip: "192.168.20.10"
  linux.vm.provider :virtualbox do |vb|
    vb.gui = false
    vb.memory = "2048"
  end
 end
end
