require 'vagrant-openstack-provider'

Vagrant.configure('2') do |config|
  
  #Enable vagrant-env plugin
  config.env.enable
  config.ssh.username = 'ubuntu'  
  config.ssh.private_key_path = ENV['OS_KEY_PATH']

  config.vm.provider :openstack do |os, override|
    os.identity_api_version = ENV['OS_IDENTITY_API_VERSION']
    os.openstack_auth_url = ENV['OS_AUTH_URL']
    os.domain_name        = ENV['OS_DOMAIN_NAME']
    os.username           = ENV['OS_USERNAME']
    os.password           = ENV['OS_PASSWORD']
    os.tenant_name        = ENV['OS_TENANT_NAME']  
    os.project_name       = ENV['OS_PROJECT_NAME']
    os.keypair_name       = ENV['OS_KEY_PAIR_NAME']
    os.region             = ENV['OS_REGION_NAME']
    os.image              = ENV['OS_IMAGE']
  end

  config.vm.define ENV['BOX_NAME'] do |s|
      
      s.vm.provider :openstack do |os, override|
        os.server_name = ENV['OS_SERVER_NAME']
        os.flavor = ENV['OS_FLAVOR']
        override.vm.synced_folder '.', '/vagrant', disabled: true
      end
      s.vm.provision "docker" do | docker |
        docker.pull_images "mongo:3.0.15-wheezy"
        docker.pull_images "cassandra:3.0.15"
      end
      s.vm.provision "docker_compose"
      config.vm.provision "shell", inline: <<-SHELL
        apt-get update
        curl -sL https://deb.nodesource.com/setup_7.x | bash -
        apt-get install -y nodejs
        apt-get install -y default-jdk
        apt-add-repository -y ppa:brightbox/ruby-ng
        apt-get update
        sudo apt-get install -y ruby2.4 ruby2.4-dev
      SHELL
  end
end
 